spring:
    profiles:
        active: dev-bootRun
    jackson:
         serialization-inclusion: NON_EMPTY
    application:
        name: OrganizationService
    rabbitmq:
        virtual-host: ${spring.profiles.active}
amqp:
    topic: OrganizationService
app:
    key: OrganizationService
    name: 企业管理
    desc: 企业管理
    version: v0.1
    termsOfServiceUrl: 
    contact:
        url:
        name:
        email:
    license:
    licenseUrl:
security:
    basic:
        enabled: true
    ignored: /health,/**/*swagger*,/**/*swagger*/**,/v2/api-docs,/webjars/**
    oauth2:
        resource:
            userInfoUri: http://dev.jyx365.top/api/v1.0/users/current
authority:
    authorities: system_service, system_web, enterprise_user, system_admin, system_operator,ROLE_ADMIN
server:
    port: 8810
logging:
    level:
        #org.springframework.ldap: DEBUG
        #org.springframework.boot.autoconfigure: DEBUG
        top.jyx365: DEBUG
        #org.springframework.core.env: DEBUG
    file: ./springboot.log
---
#单元测试
spring:
    profiles: dev-int-test
    autoconfigure:
        exclude: top.jyx365.amqp.AmqpConfig,
            top.jyx365.swagger.SwaggerConfig
    cloud:
        consul:
            config:
                enabled: false
security:
    oauth2:
        client:
            clientId: customer_care_web_server_guj
            clientSecret: 654322
            accessTokenUri: http://dev.jyx365.top/oauth/access_token
            userAuthorizationUri: http://dev.jyx365.top/sso/login
            tokenName: access_token
            #authenticationScheme: query
            #clientAuthenticationScheme: form
            scope: userinfo
        resource:
            userInfoUri: http://dev.jyx365.top/api/v1.0/users/current
server:
    port: 8710
ldap:
    password: 6Jw8fd7TfnPRd7Gr
    url: ldap://dev2.jyx365.top:389
    base: dc=development,dc=jyx365,dc=top
    userDn: cn=Manager,dc=jyx365,dc=top
---
spring:
    profiles: dev-bootRun
    rabbitmq:
        host: 121.43.38.169
        username: orgSrv
        password: uUnD1vpym3dvVxZP
security:
    oauth2:
        client:
            clientId: internal
            clientSecret: internal
            accessTokenUri: http://dev3.jyx365.cn:9999/oauth/access_token
            userAuthorizationUri: http://dev3.jyx365.cn:9999/sso/login
            tokenName: access_token
            #authenticationScheme: query
            #clientAuthenticationScheme: form
            scope: userinfo
        resource:
            tokenType: token
            tokenInfoUri: http://dev3.jyx365.cn:9999/oauth/check_token
            #userInfoUri: http://dev3.jyx365.cn:9999/api/v1.0/users/current
server:
    port: 8812
ldap:
    password: 6Jw8fd7TfnPRd7Gr
    url: ldap://dev2.jyx365.top:389
    base: dc=dev-prod,dc=jyx365,dc=top
    userDn: cn=Manager,dc=jyx365,dc=top

